log4r_config:
  # define all loggers ...
  loggers:
    - name      : production
      level     : INFO
      trace     : 'false'
      outputters :
      - custom
    - name      : development
      level     : DEBUG
      trace     : 'true'
      outputters :
      - publicweb
    - name      : publicweb
      level     : DEBUG
      trace     : 'true'
      outputters :
      - publicweb

  # define all outputters (incl. formatters)
  outputters:
  - type: DateFileOutputter
    name: datefile
    dirname: "log"
    filename: "my_app.log" # notice the file extension is needed!
    formatter:
      date_pattern: '%H:%M:%S'
      pattern     : '%d %l: %m '
      type        : PatternFormatter

  # cusom
  outputters:
  - type: FileOutputter
    name: publicweb
#    dirname: "/usr/local/src/public/test/ruby/blog/log"
    filename: "log/publicweb.log" # notice the file extension is needed!
    formatter:
      date_pattern: "%Y/%m/%d %H:%M:%S"
      pattern     : "%d %C [%l]: %M"
      type        : PatternFormatter