log4r_config:
  # define all loggers ...
  loggers:
    - name      : production
      level     : INFO
      trace     : 'false'
      outputters :
      - custom
    - name      : development
      level     : DEBUG
      trace     : 'true'
      outputters :
      - development_log
    - name      : test
      level     : DEBUG
      trace     : 'true'
      outputters :
      - publicweb

  # define all outputters (incl. formatters)
  outputters:
  - type: FileOutputter
    name: development_log
    filename: 'log/development.log'
    formatter:
      date_pattern: '%Y/%m/%d %H:%M:%S'
      pattern     : '%d [%l]: %M'
      type        : PatternFormatter
  - type: FileOutputter
    name: test_log
    filename: 'log/test.log'
    formatter:
      date_pattern: '%Y/%m/%d %H:%M:%S'
      pattern     : '%d [%l]: %M'
      type        : PatternFormatter
  - type: FileOutputter
    name: production_log
    filename: 'log/production.log'
    formatter:
      date_pattern: '%Y/%m/%d %H:%M:%S'
      pattern     : '%d [%l]: %M'
      type        : PatternFormatter